### ISSUE TITLE
Salvage unique info from schema docs formerly on main docs website

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/NMDC_documentation#54]
During this week's infrastructure meeting, @turbomam mentioned that he thought the ("merged" or "consolidated") schema documentation that—until a few days ago—was accessible via the sidebar menu of the main documentation website, contained some unique content (maybe notes, captions, comments, etc.) that does not exist in the standalone schema documentation. Multiple team members expressed an interest in preserving at least some of that content. We did not discuss specifics.

I'm creating this ticket to represent the following tasks.

### Tasks
- [ ] Identify that unique content
  > Is it in here: https://github.com/microbiomedata/NMDC_documentation/tree/main/docs/reference/metadata ?
- [ ] Determine what parts of it people want to preserve
  > We can figure out who _people_ are when we know what the content is
- [ ] Determine how anyone will preserve it
  > The _anyone_ here is whoever will be doing the preservation work
- [ ] Preserve it
  > e.g. incorporate it into the standalone schema docs or expose it directly on the main docs website
